ERROR 2025-04-11 01:05:22,121 basehttp 38540 25348 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:22,122 basehttp 38540 20432 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:24,509 basehttp 38540 20932 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:24,510 basehttp 38540 33700 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:25,348 basehttp 38540 45564 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:25,349 basehttp 38540 41348 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:25,779 basehttp 38540 44452 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:25,780 basehttp 38540 44008 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:25,959 basehttp 38540 15860 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:25,960 basehttp 38540 21020 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:26,137 basehttp 38540 5704 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:26,138 basehttp 38540 13908 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:26,372 basehttp 38540 45800 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:26,374 basehttp 38540 40340 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:26,549 basehttp 38540 29248 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:26,550 basehttp 38540 20520 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:26,711 basehttp 38540 43772 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:26,712 basehttp 38540 42240 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:26,901 basehttp 38540 32636 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:26,902 basehttp 38540 44772 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:27,114 basehttp 38540 43196 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:27,116 basehttp 38540 43412 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:33,596 basehttp 38540 15332 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:33,863 basehttp 38540 43460 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:33,909 basehttp 38540 7252 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:34,174 basehttp 38540 14128 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:59,733 basehttp 38540 15580 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:05:59,985 basehttp 38540 20508 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:06:00,044 basehttp 38540 18448 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:06:00,294 basehttp 38540 41624 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:06:09,133 basehttp 38540 37620 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:06:09,135 basehttp 38540 31068 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:06:32,557 basehttp 38540 41472 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:06:32,825 basehttp 38540 44028 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:06:32,870 basehttp 38540 44724 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:06:33,135 basehttp 38540 4188 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:08:28,977 basehttp 38540 25224 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:08:29,224 basehttp 38540 43404 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:08:29,287 basehttp 38540 9968 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:08:29,535 basehttp 38540 45476 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:09:26,773 basehttp 38540 30556 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:09:26,774 basehttp 38540 34916 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:09:41,068 basehttp 38540 39536 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:09:41,070 basehttp 38540 41464 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:09:42,564 basehttp 38540 21836 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:09:42,566 basehttp 38540 44660 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:11:00,064 basehttp 38540 44708 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:11:00,068 basehttp 38540 41856 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:11:03,686 basehttp 38540 42832 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:11:03,687 basehttp 38540 36244 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:11:04,345 basehttp 38540 46544 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:11:04,346 basehttp 38540 15860 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:11:04,549 basehttp 38540 41856 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:11:04,551 basehttp 38540 46932 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:11:04,712 basehttp 38540 46836 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:11:04,714 basehttp 38540 46840 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:12:03,781 basehttp 5632 19744 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:12:03,783 basehttp 5632 11028 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:12:05,631 basehttp 5632 45808 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:12:05,633 basehttp 5632 10364 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:12:09,109 basehttp 5632 45508 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:12:09,109 basehttp 5632 45880 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:13:42,634 basehttp 5632 28268 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 01:13:42,635 basehttp 5632 6588 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 14:55:43,645 basehttp 45932 6804 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 14:55:43,648 basehttp 45932 32344 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 14:56:00,696 basehttp 45932 27392 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 14:56:00,700 basehttp 45932 24372 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-04-11 16:08:50,189 log 50184 34824 Internal Server Error: /
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\core\views.py", line 11, in home
    return render(request, 'core/home.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_category
WARNING 2025-04-11 16:08:50,270 log 50184 17620 Not Found: /static/js/main.js
WARNING 2025-04-11 16:08:50,281 log 50184 40740 Not Found: /static/css/style.css
WARNING 2025-04-11 16:08:51,284 log 50184 14504 Not Found: /favicon.ico
ERROR 2025-04-11 16:13:24,483 log 50184 11332 Internal Server Error: /
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\core\views.py", line 11, in home
    return render(request, 'core/home.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_category
WARNING 2025-04-11 16:13:24,593 log 50184 50312 Not Found: /static/css/style.css
WARNING 2025-04-11 16:13:24,602 log 50184 47156 Not Found: /static/js/main.js
ERROR 2025-04-11 16:13:25,484 log 50184 42552 Internal Server Error: /
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\core\views.py", line 11, in home
    return render(request, 'core/home.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_category
WARNING 2025-04-11 16:13:25,531 log 50184 47152 Not Found: /static/css/style.css
WARNING 2025-04-11 16:13:25,536 log 50184 8880 Not Found: /static/js/main.js
ERROR 2025-04-11 16:13:25,854 log 50184 24724 Internal Server Error: /
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\core\views.py", line 11, in home
    return render(request, 'core/home.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_category
WARNING 2025-04-11 16:13:25,919 log 50184 46828 Not Found: /static/css/style.css
WARNING 2025-04-11 16:13:25,938 log 50184 44592 Not Found: /static/js/main.js
ERROR 2025-04-11 16:22:24,439 log 41532 30464 Internal Server Error: /
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\core\views.py", line 11, in home
    return render(request, 'core/home.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_category
WARNING 2025-04-11 16:22:24,494 log 41532 22008 Not Found: /static/css/style.css
WARNING 2025-04-11 16:22:24,498 log 41532 49020 Not Found: /static/js/main.js
ERROR 2025-04-11 16:22:25,813 log 41532 25720 Internal Server Error: /
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\core\views.py", line 11, in home
    return render(request, 'core/home.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_category
WARNING 2025-04-11 16:22:25,853 log 41532 37084 Not Found: /static/css/style.css
WARNING 2025-04-11 16:22:25,870 log 41532 49240 Not Found: /static/js/main.js
ERROR 2025-04-11 16:22:29,836 log 41532 2696 Internal Server Error: /
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\core\views.py", line 11, in home
    return render(request, 'core/home.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_category
WARNING 2025-04-11 16:22:29,921 log 41532 43504 Not Found: /static/css/style.css
WARNING 2025-04-11 16:22:29,942 log 41532 48908 Not Found: /static/js/main.js
WARNING 2025-04-11 17:08:59,082 log 8680 48200 Not Found: /static/js/main.js
WARNING 2025-04-11 17:08:59,094 log 8680 2904 Not Found: /static/images/pets-banner.jpg
WARNING 2025-04-11 17:08:59,109 log 8680 38276 Not Found: /static/css/style.css
ERROR 2025-04-11 17:09:10,368 log 8680 32104 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_utils.py", line 21, in render
    return remove_spaces(self.nodelist.render(context).strip())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_field.py", line 125, in render
    return str(field)
           ^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 281, in render
    return self._render(self.template_name, context, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 286, in _render
    return mark_safe(renderer.render(template_name, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 28, in render
    template = self.get_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 34, in get_template
    return self.engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 35, in get_template
    reraise(exc, self)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 61, in as_crispy_form
    return template.render(c)
           ^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html
WARNING 2025-04-11 17:09:10,538 log 8680 51980 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:10,547 log 8680 47880 Not Found: /static/js/main.js
WARNING 2025-04-11 17:09:15,557 log 8680 52104 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:15,575 log 8680 51268 Not Found: /static/js/main.js
ERROR 2025-04-11 17:09:20,534 log 8680 38636 Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_utils.py", line 21, in render
    return remove_spaces(self.nodelist.render(context).strip())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_field.py", line 125, in render
    return str(field)
           ^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 281, in render
    return self._render(self.template_name, context, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 286, in _render
    return mark_safe(renderer.render(template_name, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 28, in render
    template = self.get_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 34, in get_template
    return self.engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 35, in get_template
    reraise(exc, self)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 61, in as_crispy_form
    return template.render(c)
           ^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\accounts\views.py", line 95, in register
    return render(request, 'accounts/register.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html
WARNING 2025-04-11 17:09:20,640 log 8680 2276 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:20,655 log 8680 40516 Not Found: /static/js/main.js
ERROR 2025-04-11 17:09:23,825 log 8680 34924 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_utils.py", line 21, in render
    return remove_spaces(self.nodelist.render(context).strip())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_field.py", line 125, in render
    return str(field)
           ^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 281, in render
    return self._render(self.template_name, context, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 286, in _render
    return mark_safe(renderer.render(template_name, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 28, in render
    template = self.get_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 34, in get_template
    return self.engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 35, in get_template
    reraise(exc, self)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 61, in as_crispy_form
    return template.render(c)
           ^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html
WARNING 2025-04-11 17:09:23,868 log 8680 47112 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:23,885 log 8680 2696 Not Found: /static/js/main.js
ERROR 2025-04-11 17:09:27,099 log 8680 49284 Internal Server Error: /products/search/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\products\views.py", line 95, in search_products
    return render(request, 'products/search_results.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: products/search_results.html
WARNING 2025-04-11 17:09:27,154 log 8680 15648 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:27,163 log 8680 47892 Not Found: /static/js/main.js
WARNING 2025-04-11 17:09:33,138 log 8680 47472 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:33,143 log 8680 2156 Not Found: /static/js/main.js
WARNING 2025-04-11 17:09:36,841 log 8680 13456 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:36,846 log 8680 21368 Not Found: /static/js/main.js
WARNING 2025-04-11 17:09:38,379 log 8680 47948 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:38,389 log 8680 48168 Not Found: /static/js/main.js
WARNING 2025-04-11 17:09:38,398 log 8680 50324 Not Found: /static/images/pets-banner.jpg
WARNING 2025-04-11 17:09:39,363 log 8680 48908 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:39,369 log 8680 38580 Not Found: /static/images/pets-banner.jpg
WARNING 2025-04-11 17:09:39,377 log 8680 47560 Not Found: /static/js/main.js
ERROR 2025-04-11 17:09:41,738 log 8680 48536 Internal Server Error: /cart/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\cart\views.py", line 37, in cart_detail
    return render(request, 'cart/cart_detail.html', {'cart': cart})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'multiply'
WARNING 2025-04-11 17:09:41,798 log 8680 14380 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:41,803 log 8680 48160 Not Found: /static/js/main.js
ERROR 2025-04-11 17:09:53,062 log 8680 44312 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_utils.py", line 21, in render
    return remove_spaces(self.nodelist.render(context).strip())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_field.py", line 125, in render
    return str(field)
           ^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 281, in render
    return self._render(self.template_name, context, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 286, in _render
    return mark_safe(renderer.render(template_name, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 28, in render
    template = self.get_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 34, in get_template
    return self.engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 35, in get_template
    reraise(exc, self)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 61, in as_crispy_form
    return template.render(c)
           ^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html
WARNING 2025-04-11 17:09:53,107 log 8680 48688 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:53,124 log 8680 31612 Not Found: /static/js/main.js
ERROR 2025-04-11 17:09:58,092 log 8680 50024 Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_utils.py", line 21, in render
    return remove_spaces(self.nodelist.render(context).strip())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_field.py", line 125, in render
    return str(field)
           ^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 281, in render
    return self._render(self.template_name, context, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 286, in _render
    return mark_safe(renderer.render(template_name, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 28, in render
    template = self.get_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 34, in get_template
    return self.engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 35, in get_template
    reraise(exc, self)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 61, in as_crispy_form
    return template.render(c)
           ^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\accounts\views.py", line 95, in register
    return render(request, 'accounts/register.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html
WARNING 2025-04-11 17:09:58,136 log 8680 49264 Not Found: /static/css/style.css
WARNING 2025-04-11 17:09:58,155 log 8680 28212 Not Found: /static/js/main.js
WARNING 2025-04-11 17:12:37,628 log 8680 13920 Not Found: /static/css/style.css
WARNING 2025-04-11 17:12:37,633 log 8680 48280 Not Found: /static/js/main.js
ERROR 2025-04-11 17:12:42,337 log 8680 16068 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_utils.py", line 21, in render
    return remove_spaces(self.nodelist.render(context).strip())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_field.py", line 125, in render
    return str(field)
           ^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 281, in render
    return self._render(self.template_name, context, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 286, in _render
    return mark_safe(renderer.render(template_name, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 28, in render
    template = self.get_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 34, in get_template
    return self.engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 35, in get_template
    reraise(exc, self)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 61, in as_crispy_form
    return template.render(c)
           ^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html
WARNING 2025-04-11 17:12:42,387 log 8680 50044 Not Found: /static/css/style.css
WARNING 2025-04-11 17:12:42,407 log 8680 49224 Not Found: /static/js/main.js
WARNING 2025-04-11 17:28:39,269 log 15060 49324 Not Found: /static/css/style.css
WARNING 2025-04-11 17:28:39,278 log 15060 38840 Not Found: /static/images/pets-banner.jpg
WARNING 2025-04-11 17:28:39,286 log 15060 50108 Not Found: /static/js/main.js
WARNING 2025-04-11 17:28:40,348 log 15060 50196 Not Found: /static/css/style.css
WARNING 2025-04-11 17:28:40,354 log 15060 24856 Not Found: /static/images/pets-banner.jpg
WARNING 2025-04-11 17:28:40,365 log 15060 13456 Not Found: /static/js/main.js
WARNING 2025-04-11 17:28:41,903 log 15060 47444 Not Found: /static/css/style.css
WARNING 2025-04-11 17:28:41,915 log 15060 48260 Not Found: /static/js/main.js
ERROR 2025-04-11 17:28:45,175 log 15060 6124 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_utils.py", line 21, in render
    return remove_spaces(self.nodelist.render(context).strip())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_field.py", line 125, in render
    return str(field)
           ^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 281, in render
    return self._render(self.template_name, context, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 286, in _render
    return mark_safe(renderer.render(template_name, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 28, in render
    template = self.get_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 34, in get_template
    return self.engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 35, in get_template
    reraise(exc, self)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 61, in as_crispy_form
    return template.render(c)
           ^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html
WARNING 2025-04-11 17:28:45,229 log 15060 48396 Not Found: /static/css/style.css
WARNING 2025-04-11 17:28:45,240 log 15060 7156 Not Found: /static/js/main.js
WARNING 2025-04-11 17:28:49,466 log 15060 19304 Not Found: /static/css/style.css
WARNING 2025-04-11 17:28:49,473 log 15060 27716 Not Found: /static/images/pets-banner.jpg
WARNING 2025-04-11 17:28:49,489 log 15060 15684 Not Found: /static/js/main.js
ERROR 2025-04-11 17:28:57,213 log 15060 22392 Internal Server Error: /products/search/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\products\views.py", line 95, in search_products
    return render(request, 'products/search_results.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: products/search_results.html
WARNING 2025-04-11 17:28:57,257 log 15060 41532 Not Found: /static/css/style.css
WARNING 2025-04-11 17:28:57,261 log 15060 48036 Not Found: /static/js/main.js
WARNING 2025-04-11 18:05:47,665 log 31784 50656 Not Found: /static/js/main.js
WARNING 2025-04-11 18:05:47,672 log 31784 26332 Not Found: /static/css/style.css
ERROR 2025-04-11 18:05:49,885 log 31784 39376 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_utils.py", line 21, in render
    return remove_spaces(self.nodelist.render(context).strip())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_field.py", line 125, in render
    return str(field)
           ^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 281, in render
    return self._render(self.template_name, context, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\widgets.py", line 286, in _render
    return mark_safe(renderer.render(template_name, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 28, in render
    template = self.get_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\forms\renderers.py", line 34, in get_template
    return self.engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 35, in get_template
    reraise(exc, self)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 61, in as_crispy_form
    return template.render(c)
           ^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\xampp\htdocs\shoppet\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: captcha/widget_v2_checkbox.html
WARNING 2025-04-11 18:05:49,925 log 31784 49776 Not Found: /static/css/style.css
WARNING 2025-04-11 18:05:49,937 log 31784 40372 Not Found: /static/js/main.js
WARNING 2025-04-11 18:28:13,095 log 31784 17836 Not Found: /static/css/style.css
WARNING 2025-04-11 18:28:13,485 log 31784 49536 Not Found: /static/images/pets-banner.jpg
WARNING 2025-04-11 18:28:13,498 log 31784 53360 Not Found: /static/js/main.js
WARNING 2025-04-11 18:28:13,515 log 31784 49296 Not Found: /favicon.ico
